site_name: Quantum & Cryptography Docs
site_description: A collection of my learnings and projects on Quantum Computing and Cryptography.
site_author: Your Name
theme: 
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
    #- media: "(prefers-color-scheme: dark)"
    #  scheme: slate
    #  primary: deep purple
    #  accent: light blue
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - math 
  #logo: assets/logo.png  # Optional: Add a custom logo
  favicon: assets/favicon.ico  # Optional: Add a favicon

# Navigation structure
nav:
  - Home: index.md
  - Math Fundamentals:
      - Modular Arithmetic: Math_Fundamentals/modular_arithmetic.md
      - Logic Gates: Math_Fundamentals/logic_gates.md
      - Linear Algebra: 
        - Tensor: Math_Fundamentals/linear_algebr_tensor.md
        - Matrices: Math_Fundamentals/matrices.md
      - Hilbert Space: Math_Fundamentals/hilbert_space.md
  - Quantum Mechanics:
      - Basics:
        - Qubit(s): quantum_mechanics/Qubit.md
        - Quantum gates: quantum_mechanics/Quantum_logic_gates.md
        - The Bloch sphere and rotations: quantum_mechanics/TheBlochSphereAndRotation.md
      - Theorems:
        - No-cloning: quantum_mechanics/No-cloing.md
        - No-deleting: quantum_mechanics/No-deleting.md
        - No-hiding: quantum_mechanics/No-hiding.md
        - No-teleportation: quantum_mechanics/No-teleportation.md
  - Quantum Computing:
      # - Quantum Mechanics
      # - Pauli matrices
      - Basics: 
        - Basics: quantum/basics.md
        - Algorithms: quantum/algorithms.md
      - Quantum Computation: quantum/computation.md
      - Applications: quantum/applications.md
  - Cryptography:
      - Fundamentals: cryptography/fundamentals.md
      - Symmetric Cryptography: cryptography/symmetric.md
      - Asymmetric Cryptography: cryptography/asymmetric.md
      - Quantum Cryptography: cryptography/quantum.md
  - Quantum Cryptography:
      - Fundamentals: qcryptography/fundamentals.md
      - QKD: 
        - BB84: qcryptography/BB84.md
  - Quantum machine learning and optimization:
      - Optimization Algorithms:
        - Quadratic Unconstrained Binary Optimization (QUBO): 
          - QUBO Intro: QuantumOpt/QUBO.md
          - QUBO Example: QuantumOpt/QUBO_1_start.ipynb
          - QUBO Knapsack: QuantumOpt/QUBO_example_knapsack_qiskit.ipynb
          - QUBO Max-Cut and TSP: QuantumOpt/QUBO_example_max_cut_and_tsp_qiskit.ipynb
        - Adiabatic Quantum Computing & Quantum Annealing (AQQA): 
          - AQQA Intro: QuantumOpt/AQQA.md
          - AQQA Example: QuantumOpt/AQQA_D-WAVE.ipynb
        - Quantum Approximate Optimization Algorithm (QAOA): 
          - QAOA Intro: QuantumOpt/QAOA.md
          - QAOA D-Wave Example: QuantumOpt/QAOA_D-Wave.ipynb.ipynb
          - QAOA PennyLane Example: QuantumOpt/QAOA_PennyLane.ipynb
        - Grover Adaptive Search (GAS): 
          - GAS Intro: QuantumOpt/GAS.md
          - GAS Example: QuantumOpt/GAS_Qiskit_molecule.ipynb
        - Variational Quantum Eignesolver (VQE): 
          - VQE Intro: QuantumOpt/VQEIntro.md
          - VQE Example: QuantumOpt/VQE_Qiskit_molecule.ipynb
      - Optimization Machine Learning:
        - Machine Learning Refresher: QuantumOpt/MachineLearningRefresher.md
        - Quantum Support Vector Machines: 
          - QSVM Intro: QuantumOpt\QML\QSVM.md
        - Quantum Neural Networks: 
          - QNN Intro: QuantumOpt\QML\QNN.md
        - Quantum Hybrid Architectures: 
          - QHybrid Intro: QuantumOpt\QML\QHyb.md
        - Quantum Generative Adversarial Networks: 
          - QGANS Intro: QuantumOpt\QML\QGANS.md

  - Real-world projects:
      - Quantum Computing Tools: projects/QuantumComputingTools.md
      - Quantum Simulations: projects/quantum-simulations.md
      - Cryptography Implementations: projects/crypto-implementations.md
  - About Me: about.md

# Plugins
plugins:
  - mkdocs-jupyter
  - glightbox
#  - mathjax
#  - open-in-new-tab 

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML
  #- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
  #- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.2.4/mermaid.min.js

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  
  # Font Formatting: https://squidfunk.github.io/mkdocs-material/reference/formatting/
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # List: https://squidfunk.github.io/mkdocs-material/reference/lists/
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # Callout: https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/pcchouCR97/mkdocs-material-tutorial
    - icon: fontawesome/brands/twitter
      link: https://x.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/po-chih-chou-0638941ab/
  
  mathjax_config: |
    MathJax = {
      tex: {
        macros: {
          ket: ["\\left|#1\\right\\rangle", 1]
        }
      }
    };

copyright: |
  &copy; 2024-2025 <a href="https://github.com/pcchouCR97"  target="_blank" rel="noopener">Po-Chih Chou</a>